# Generated by Django 4.2.7 on 2023-11-14 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('HOME', 'дома'), ('WORK', 'на работе'), ('EVERYWHERE', 'везде')], default='everywhere', verbose_name='место')),
                ('habit_time', models.TimeField(verbose_name='время')),
                ('habit_action', models.CharField(max_length=255, verbose_name='действие')),
                ('periodicity', models.CharField(choices=[('DAILY', 'ежедневно'), ('WEEKLY', 'еженедельно'), ('WEEKDAYS', 'по будням'), ('WEEKEND', 'по выходным')], default='daily', verbose_name='периодичность')),
                ('is_nice', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('reward', models.CharField(blank=True, max_length=1000, null=True, verbose_name='вознаграждение')),
                ('execute_time', models.PositiveSmallIntegerField(verbose_name='время выполнения')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('connect_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atomichabit.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
