# Generated by Django 4.2.7 on 2023-11-20 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('atomichabit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='date_add',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[('DAILY', 'ежедневно'), ('WEEKLY', 'еженедельно'), ('WEEKDAYS', 'по будням'), ('WEEKENDS', 'по выходным')], default='daily', verbose_name='периодичность'),
        ),
    ]
