# Generated by Django 4.2.7 on 2023-11-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomichabit', '0003_habit_date_add_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[('DAILY', 'ежедневно'), ('WEEKLY', 'еженедельно'), ('WEEKDAYS', 'по будням'), ('WEEKENDS', 'по выходным')], default='DAILY', verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(default='везде', max_length=150, verbose_name='место'),
        ),
    ]
